### ISSUE TITLE
Is not a constructor

### ISSUE THREAD

**Issue by alekitopi** [jbis9051/paypal-simple#1]
```
/home/alekitopi/paypal-web/checkout.js:3
const payPalSimple = new PayPalSimple("*client-id*", "*secret*", true);
                     ^

TypeError: PayPalSimple is not a constructor
    at Object.<anonymous> (/home/alekitopi/paypal-web/checkout.js:3:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by jbis9051** [comment]
@alekitopi  Please post how you are importing/requiring the module.
